# Generated by Django 2.0.3 on 2018-04-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('comlete', models.BooleanField(default=False)),
                ('tmt_counts', models.IntegerField(default=1)),
                ('complete_counts', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('done_time', models.DateTimeField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('summary', models.TextField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_project.Label')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_project.List')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_mins', models.IntegerField(default=25)),
                ('relax_mins', models.IntegerField(default=5)),
                ('relax_long_mins', models.IntegerField(default=20)),
                ('relax_long_count', models.IntegerField(default=4)),
                ('use_notification', models.BooleanField(default=True)),
                ('auto_focus', models.BooleanField(default=False)),
                ('auto_relax', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_project.User')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_project.Status'),
        ),
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_project.User'),
        ),
    ]
