# Generated by Django 2.0.3 on 2018-04-06 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_project', '0002_auto_20180406_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='_project.User'),
            preserve_default=False,
        ),
    ]
