# Generated by Django 2.0.3 on 2018-04-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_project', '0003_auto_20180407_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='complete_counts',
            field=models.IntegerField(default=0),
        ),
    ]
