# Generated by Django 2.0.3 on 2018-04-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_project', '0004_auto_20180407_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='comlete',
            new_name='complete',
        ),
    ]
