# Generated by Django 2.0.3 on 2018-04-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_project', '0006_countmins'),
    ]

    operations = [
        migrations.AddField(
            model_name='countmins',
            name='count_promos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promo',
            name='label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='_project.Label'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countmins',
            name='count_mins',
            field=models.IntegerField(default=0),
        ),
    ]
