# Generated by Django 2.0.3 on 2018-04-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_project', '0007_auto_20180408_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='countmins',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='_project.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='_project.User'),
            preserve_default=False,
        ),
    ]
