# Generated by Django 2.0.3 on 2018-04-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_project', '0008_auto_20180408_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountMins',
            new_name='Count',
        ),
    ]
