# Generated by Django 2.0.3 on 2018-04-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_project', '0009_auto_20180409_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
