# Generated by Django 2.0.3 on 2018-04-11 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_project', '0010_auto_20180409_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_project.User')),
            ],
        ),
    ]
