# Generated by Django 2.0.3 on 2018-04-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_project', '0012_userfirstin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='status',
        ),
        migrations.AddField(
            model_name='promo',
            name='pro_mins',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
